"""
Clean comprehensive test coverage excluding ingest tests that mock utils.progress
This ensures proper progress module coverage recording without mocking conflicts
Updated: 2025-09-05 - Clean version without progress-mocking ingest tests
"""

# Import all verified working test classes with correct names
import sys
import os
sys.path.append(os.path.dirname(__file__))

# PROGRESS MODULE - IMPORT FIRST WITH CLEAN TESTS
from test_progress_isolated_coverage import TestProgressIsolated

# BACKEND_LIB MODULE - Verified working tests
from test_backend_lib_90_percent import TestBackendLib90Percent
from test_backend_lib_comprehensive import TestBackendLibComprehensive

# CSV_DETECTOR MODULE - ALL 5 FILES FOR MAXIMUM 95% COVERAGE!
from test_csv_detector_90_percent import TestCSVDetector90Percent
from test_csv_detector_exception_coverage import TestCSVDetectorExceptionCoverage
from test_csv_detector_final import TestCSVDetectorFinalCoverage
from test_csv_detector_complete import TestCSVDetectorExceptionHandling, TestCSVDetectorTextQualifierEdgeCases, TestCSVDetectorHeaderDetection, TestCSVDetectorTrailerDetection, TestCSVDetectorIntegrationEdgeCases
from test_csv_detector_final_push import TestCSVDetectorFinalPush

# LOGGER MODULE - ALL 3 FILES FOR MAXIMUM 98% COVERAGE!
from test_logger_90_percent import TestLoggerComprehensive, TestDatabaseLoggerComprehensive, TestLoggerEdgeCases
from test_logger_comprehensive import TestLoggerBasicLogging, TestLoggerWriteLog, TestLoggerReading, TestLoggerMaintenance, TestDatabaseLogger
from test_logger_100_percent import TestLoggerZoneInfoImport, TestLoggerExceptionHandling, TestDatabaseLoggerExceptionHandling, TestLoggerFileIOExceptions, TestLoggerEdgeCases as TestLoggerEdgeCases100, TestDatabaseLoggerAdvanced
from test_logger_final_100 import TestZoneInfoImportFallback, TestGetLogsExceptionCoverage, TestDatabaseTimestampExceptionCoverage, TestComplexExceptionScenarios

# FILE_MONITOR MODULE - ALL 9 FILES FOR MAXIMUM 100% COVERAGE!
from test_file_monitor_100_percent import TestFileMonitor100Percent
from test_file_monitor_90_percent import TestFileMonitor90Percent
from test_file_monitor_complete_coverage import TestFileMonitorCompleteCoverage
from test_file_monitor_complete import TestFileMonitorComplete, TestFileMonitorProcessing, TestFileMonitorMainLoop, TestFileMonitorMain
from test_file_monitor_extended import TestFileMonitorExtended
from test_file_monitor_final_push import TestFileMonitorFinalPush
from test_file_monitor_final import TestFileMonitorFinal
from test_file_monitor_focused import TestFileMonitorFocused
from test_file_monitor_remaining import TestFileMonitorRemaining

# FILE_HANDLER MODULE - ALL 5 FILES FOR MAXIMUM 100% COVERAGE!
from test_file_handler_comprehensive import TestFileHandlerInit, TestFileHandlerUploadedFiles, TestFileHandlerFormatFiles, TestFileHandlerUtilities, TestFileHandlerValidation
from test_file_handler_complete import TestFileHandlerAsyncOperations, TestFileHandlerUtilityMethods, TestFileHandlerEdgeCases
from test_file_handler_targeted import TestFileHandlerTargetedCoverage
from test_file_handler_working import TestFileHandlerWorking
from test_file_handler_90_percent import TestFileHandlerAsyncMethods

# BASIC FUNCTIONALITY - Verified working tests
from test_basic_functionality import TestBasicFunctionality

# DATABASE MODULE - ALL 15 FILES FOR MAXIMUM 90% COVERAGE!
from test_database_simple import TestDatabaseBasics
from test_database_next_level import TestDatabaseManagerNextLevel
from test_database_final_push import TestDatabaseManagerFinalPush
from test_database_extended_coverage import TestDatabaseManagerExtendedCoverage
from test_database_focused import TestDatabaseManagerInit, TestDatabaseConnections, TestDatabaseSchemaOperations, TestDatabaseUtilities, TestDatabaseErrorHandling, TestDatabaseThreadSafety
from test_database_90_percent import TestDatabaseManager90Percent
from test_database_90_percent_push import TestDatabaseManager90PercentPush
from test_database_comprehensive import TestDatabaseBackupOperations, TestDatabaseConnectionPooling, TestDatabaseErrorHandling, TestDatabaseManagerInit as TestDatabaseManagerInitComp, TestDatabaseOperations, TestDatabaseUtilityMethods
from test_database_additional import TestDatabaseAdditionalMethods
from test_database_critical_coverage import TestDatabaseManagerCriticalCoverage
from test_database_ultimate_90 import TestDatabaseManagerUltimate90
from test_database_final_90_push import TestDatabaseManagerFinal90Push

# NEW: DATABASE ERROR PATHS COVERAGE - 24 COMPREHENSIVE TESTS FOR 90% TOTAL COVERAGE!
from test_database_error_paths_coverage import (
    TestDatabaseManagerErrorPaths,
    TestDatabaseBackupOperations as TestDatabaseBackupOperationsErrorPaths,
    TestDatabaseConfigurationEdgeCases,
    TestDatabaseDataTypeNormalization,
    TestDatabaseConnectionPooling as TestDatabaseConnectionPoolingErrorPaths
)

# INGEST MODULE - ONLY NON-PROGRESS-MOCKING TESTS
# Include ingest tests that don't mock utils.progress functions
from test_ingest_comprehensive import TestDataIngesterInit, TestDataIngesterUtilityMethods, TestDataIngesterCSVReading, TestDataIngesterMainIngestion, TestDataIngesterDatabaseLoading
from test_ingest_90_percent import TestDataIngester90Percent
from test_ingest_complete_coverage import TestDataIngesterCompleteCoverage
from test_ingest_80_percent_comprehensive import TestDataIngester80PercentComprehensive
from test_ingest_error_handling_comprehensive import TestDataIngesterErrorHandling
from test_ingest_advanced_coverage import TestDataIngesterAdvancedCoverage
from test_ingest_core_loading import TestDataIngesterCoreLoading
from test_ingest_working_comprehensive import TestDataIngesterWorking
from test_ingest_simple_push import TestDataIngesterSimplePush
from test_ingest_push_to_90_systematic import TestDataIngesterSystematic90
from test_ingest_push_to_90 import TestDataIngesterPushTo90

# EXCLUDE these ingest tests that mock utils.progress:
# - test_ingest_final_70_plus (has extensive utils.progress mocking)
# - test_ingest_core_workflow_coverage (mocks utils.progress functions)
# - test_ingest_70_percent_final_push (mocks utils.progress functions)
# - test_ingest_90_percent_final (mocks utils.progress functions)
# - Any other ingest tests that use patch('utils.progress.*')